FROM mcr.microsoft.com/dotnet/sdk:10.0 AS base
USER $APP_UID
EXPOSE 8080
EXPOSE 8081

COPY bin/Release/net10.0/publish/ app/
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
RUN dotnet dev-certs https -v -ep openiddict.pfx -p 9967cb28-4661-4463-8b9d-b755fed9d7b9
RUN chmod 644 openiddict.pfx

FROM base AS final
WORKDIR /app
COPY --from=build /src .

ENTRYPOINT ["dotnet", "BillSharing.Web.dll"]